spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://47.108.198.18/mybatis_puls?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 654321
    driver-class-name: com.mysql.cj.jdbc.Driver

#日志配置；；；真实开发时，日志不用配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#逻辑删除配置
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

